spring:
  application:
    name: product-service
  profiles:
    active: localhost
  output:
    ansi:
      enabled: always
  main:
    allow_bean_definition_overriding: true
info:
  component: Product Service

server:
  port: 9788
#logging:
#  level:
#    root: off
#    com.mustafatatlikatik: debug

---
spring:
  profiles: localhost
  cloud:
    config:
      url:http://localhost:9788
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: stock_management
  datasource:
    url: "jdbc:postgresql://localhost:5432/stock_management"
    username: postgres
    password: 12345

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

---
spring:
  profiles: stage
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: stock_management
  datasource:
    url: "jdbc:postgresql://postgres:5432/stock_management"
    username: postgres
    password: 12345

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    instance-id: ${spring.application.name}:${random.uuid}