version: '3.3'

services:
  product-cache-service:
    hostname: product-cache-service
    image: product-cache-service:0.0.2
    networks:
      - stock-management-network-backend
    expose:
      - 9791
    ports:
      - 9791:9791
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        reservations:
          cpus: "0.50"
          memory: 512M
        limits:
          cpus: "1.0"
          memory: 1G
    environment:
      - "SPRING_PROFILES_ACTIVE=stage"
    entrypoint: [ "java","-jar","app.jar" ]

networks:
  stock-management-network-backend: