spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_seller?currentSchema=sc_book&ssl=false
    username: admin
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-circular-references: true

app:
  jwt:
    secret: RandomSecretKey
    expiration-in-ms: 86400000
